### PR TITLE
Fixes #1146 - Namespace para *FAILURE* na função *getTaskResult*.

### LINKED ISSUE #1146: Espaço de nomes para resultados tipo *FAILURE* da função *getTaskResult*
Deve ser implementado um espaço de nomes para a representação dos diferentes 
tipos de erro, que podem ocorrer durante a execução das tarefas assíncronas, 
na estrutura retornada pela função *getTaskResult*. 

O espaço de nomes segue o modelo do header ``errno.h`` presente na biblioteca 
padrão da linguagem C, onde números inteiros são utilizados para representar 
tipos de erros.

Detalhes em: https://github.com/scieloorg/scielo-manager/blob/beta/docs/dev/rpc_spec/addArticle.rst

errno | Tipo             | Descrição                                                
------|------------------|----------
1     | DuplicationError | O artigo representado por ``xml_string`` já havia sido adicionado anteriormente
2     | ValueError       | ``xml_string`` é mal-formado ou apresenta algum problema estrutural que impeça sua identificação

### PR DESCRIPTION
**Pull request by gustavofonseca**

### CODE REVIEW

**Comment by gustavofonseca** [comment]
Vou conferir algumas coisas sem alcool no organismo.

**Comment by jamilatta** [comment]
Quase impossível...., mas confiamos em vc.

On Mon, Jul 6, 2015 at 11:33 AM, Gustavo Fonseca <notifications@github.com>
wrote:

> Vou conferir algumas coisas sem alcool no organismo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/pull/1150#issuecomment-118873930>
> .
>



-- 

Jamil Atta Junior

**Comment by jfunez** [comment]
:beers:

**Comment by gustavofonseca** [comment]
Quase impossível de eu estar sem álcool no organismo ou conferir as coisas? rs

**Comment by jamilatta** [comment]
Sem álcool no organismo!!!! rs

On Mon, Jul 6, 2015 at 11:38 AM, Gustavo Fonseca <notifications@github.com>
wrote:

> Quase impossível de eu estar sem álcool no organismo ou conferir as
> coisas? rs
> > On 06/07/2015, at 11:37, Juan Funez <notifications@github.com> wrote:
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/scieloorg/scielo-manager/pull/1150#issuecomment-118874882
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/pull/1150#issuecomment-118875258>
> .
>



-- 

Jamil Atta Junior

**Pull request closed without merging**
